server:
  port: 8091
spring:
  devtools:
    livereload:
      port: 35740

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
logging:
  level:
    org.apache.kafka: warn
