# noinspection ComposeUnknownKeys
include:
  - compose-environment.yml

services:
  producer-service:
    build:
      context: ../../
      dockerfile: docker/producer-service.Dockerfile
    networks:
      - app-tier
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '8090:8090'
    container_name: producer-service
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
    depends_on:
      init-kafka:
        condition: service_completed_successfully

  consumer-service:
    build:
      context: ../../
      dockerfile: docker/consumer-service.Dockerfile
    networks:
      - app-tier
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '8091:8091'
    container_name: consumer-service
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
    depends_on:
      init-kafka:
        condition: service_completed_successfully
